// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Report.Web.EF;

#nullable disable

namespace Report.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221204120318_addniftyweeklytable")]
    partial class addniftyweeklytable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Report.Web.EF.NiftyWeekly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("float");

                    b.Property<double>("CloseFrmY")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DayLowToHigh")
                        .HasColumnType("float");

                    b.Property<DateTime>("DayMaxHighReachedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DayMaxLowReachedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Gap")
                        .HasColumnType("float");

                    b.Property<double>("High")
                        .HasColumnType("float");

                    b.Property<double>("HighFrmY")
                        .HasColumnType("float");

                    b.Property<double>("Low")
                        .HasColumnType("float");

                    b.Property<double>("LowFrmY")
                        .HasColumnType("float");

                    b.Property<double>("Open")
                        .HasColumnType("float");

                    b.Property<double>("PrevDayClose")
                        .HasColumnType("float");

                    b.Property<double>("_10AM")
                        .HasColumnType("float");

                    b.Property<double>("_10_30AM")
                        .HasColumnType("float");

                    b.Property<double>("_1PM")
                        .HasColumnType("float");

                    b.Property<double>("_2PM")
                        .HasColumnType("float");

                    b.Property<double>("_2_25PM")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NiftyWeekly");
                });
#pragma warning restore 612, 618
        }
    }
}
